(function(g){var window=this;'use strict';var bA=function(p,C){g.L.call(this,{L:"button",i_:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},j:[{L:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},j:[{L:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},j:[{L:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
j:[{L:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.N=p;this.listen("click",this.onClick,this);this.updateValue("title",g.kj(p,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.A_(C.aI(),this.element))},d_E=function(p){g.L.call(this,
{L:"div",
B:"ytp-miniplayer-ui"});this.J=this.W=!1;this.player=p;this.U(p,"minimized",this.xq);this.U(p,"onStateChange",this.YVx);this.U(p,"documentpictureinpicturechange",this.OSY)},iEF=function(p,C){g.Tz(p.player.getRootNode(),"ytp-player-minimized",C);
p.player.G("web_cairo_modern_miniplayer")&&g.Tz(p.player.getRootNode(),"ytp-modern-miniplayer",C);p.player.G("web_cairo_modern_miniplayer_inset_progress_bar")&&g.Tz(p.player.getRootNode(),"ytp-miniplayer-alternate-ui",C)},hpr=function(p){var C=p.player.dV().getPlayerSize().width,V=0,N=C;
if(p.player.G("web_cairo_modern_miniplayer")&&!p.J&&!p.player.G("web_cairo_modern_miniplayer_infobar")||p.player.G("web_cairo_modern_miniplayer_inset_progress_bar"))V=12,N=C-24;g.cs1(p.progressBar,V,N,!1);g.GI(p.progressBar)},ssF=function(p){g.IT.call(this,p);
this.C=new g.Rr(this);this.T=new d_E(this.player);this.T.hide();g.LT(this.player,this.T.element,4);p.isMinimized()&&(this.load(),g.Tz(p.getRootNode(),"ytp-player-minimized",!0))};
g.m(bA,g.L);bA.prototype.onClick=function(){this.N.Jk("onExpandMiniplayer")};g.m(d_E,g.L);g.h=d_E.prototype;
g.h.show=function(){this.T=new g.V2(this.hD,null,this);this.T.start();if(!this.W){this.tooltip=new g.Ao(this.player,this);g.R(this,this.tooltip);g.LT(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.WV=new g.iW(this.player);g.R(this,this.WV);this.progressBar=new g.Bz(this.player,this);g.R(this,this.progressBar);g.LT(this.player,this.progressBar.element,4);this.player.G("web_cairo_modern_miniplayer_infobar")&&g.Ed(this.player.getRootNode(),"ytp-always-showing-infobar");this.C=new g.L({L:"div",
B:"ytp-miniplayer-scrim"});g.R(this,this.C);this.C.u_(this.element);this.U(this.C.element,"click",this.RQ);var p=new g.L({L:"button",i_:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},j:[g.yD()]});g.R(this,p);p.u_(this.C.element);this.U(p.element,"click",this.MK);p=new bA(this.player,this);g.R(this,p);p.u_(this.C.element);this.V=new g.L({L:"div",B:"ytp-miniplayer-controls"});g.R(this,this.V);this.V.u_(this.C.element);this.player.G("web_cairo_modern_miniplayer")||this.U(this.V.element,
"click",this.RQ);var C=new g.L({L:"div",B:"ytp-miniplayer-button-container"});g.R(this,C);C.u_(this.V.element);p=new g.L({L:"div",B:"ytp-miniplayer-play-button-container"});g.R(this,p);p.u_(this.V.element);var V=new g.L({L:"div",B:"ytp-miniplayer-button-container"});g.R(this,V);V.u_(this.V.element);this.Z=new g.LZ(this.player,this,!1);g.R(this,this.Z);this.Z.u_(C.element);C=new g.$X(this.player,this);g.R(this,C);C.u_(p.element);this.nextButton=new g.LZ(this.player,this,!0);g.R(this,this.nextButton);
this.nextButton.u_(V.element);this.D=this.player.G("web_cairo_modern_miniplayer")?new g.Ua(this.player,this,0):new g.Ua(this.player,this);g.R(this,this.D);this.D.u_(this.C.element);this.S=new g.L({L:"div",B:"ytp-miniplayer-buttons"});g.R(this,this.S);g.LT(this.player,this.S.element,4);p=new g.L({L:"button",i_:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},j:[g.yD()]});g.R(this,p);p.u_(this.S.element);this.U(p.element,"click",this.MK);p=new g.L({L:"button",i_:["ytp-miniplayer-replay-button",
"ytp-button"],X:{"aria-label":"Close"},j:[g.k0()]});g.R(this,p);p.u_(this.S.element);this.U(p.element,"click",this.dWn);this.player.G("web_cairo_modern_miniplayer")&&(p=new bA(this.player,this),g.R(this,p),p.u_(this.S.element));this.U(this.player,"presentingplayerstatechange",this.ey);this.U(this.player,"appresize",this.OR);this.U(this.player,"fullscreentoggled",this.OR);this.player.G("web_cairo_modern_miniplayer")&&this.U(this.player,"onPlaylistUpdate",this.wd);this.OR();this.W=!0}this.player.getPlayerState()!==
0&&g.L.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.h.hide=function(){this.T&&(this.T.dispose(),this.T=void 0);g.L.prototype.hide.call(this);this.player.isMinimized()||(this.W&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.h.CS=function(){this.T&&(this.T.dispose(),this.T=void 0);g.L.prototype.CS.call(this)};
g.h.MK=function(){this.player.G("kevlar_watch_while_v2")||this.player.stopVideo();this.player.Jk("onCloseMiniplayer")};
g.h.dWn=function(){this.player.playVideo()};
g.h.RQ=function(p){if(p.target===this.C.element||p.target===this.V.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.h.xq=function(){iEF(this,this.player.isMinimized());this.player.G("web_cairo_modern_miniplayer")&&this.wd()};
g.h.OSY=function(){iEF(this,this.player.l0());this.player.G("web_cairo_modern_miniplayer")&&this.wd();g.Tz(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.l0())};
g.h.Nn=function(){this.progressBar.m6();this.D.m6()};
g.h.hD=function(){this.Nn();this.T&&this.T.start()};
g.h.ey=function(p){g.r(p.state,32)&&this.tooltip.hide()};
g.h.wd=function(){this.J=(this.player.isMinimized()||this.player.l0())&&!!this.player.getPlaylist();g.Tz(this.player.getRootNode(),"ytp-has-playlist-data",this.J);hpr(this)};
g.h.OR=function(){hpr(this)};
g.h.YVx=function(p){this.player.isMinimized()&&(p===0?this.hide():this.show())};
g.h.aI=function(){return this.tooltip};
g.h.Lr=function(p,C,V,N,H){var X=0,d=0,a=0,E=g.Ax(p);N=C&&(g.aL(C,"ytp-prev-button")||g.aL(C,"ytp-next-button"));if(C){V=g.aL(C,"ytp-play-button");var l=g.aL(C,"ytp-miniplayer-expand-watch-page-button");N?X=a=12:V?(C=g.I9(C,this.element),a=C.x,X=C.y-12):l&&(a=g.aL(C,"ytp-miniplayer-button-top-left"),X=g.I9(C,this.element),C=g.Ax(C),a?(a=8,X=X.y+40):(a=X.x-E.width+C.width,X=X.y-20))}else a=V-E.width/2,d=25+(H||0);C=this.player.dV().getPlayerSize();H=X+(H||0);E=g.J9(a,0,C.width-E.width-12);H?(p.style.top=
H+"px",p.style.bottom=""):(p.style.top="",p.style.bottom=d+"px");p.style.left=E+"px";this.player.G("web_cairo_modern_miniplayer")&&(d=g.aL(p,"ytp-preview"),p.style.visibility=N&&d&&C.height<225?"hidden":"")};g.m(ssF,g.IT);g.h=ssF.prototype;g.h.onVideoDataChange=function(){if(this.player.getVideoData()){var p=this.player.getVideoAspectRatio(),C=16/9;p=p>C+.1||p<C-.1;g.Tz(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",p)}};
g.h.create=function(){g.IT.prototype.create.call(this);this.C.U(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.h.P_=function(){return!1};
g.h.load=function(){this.player.hideControls();this.T.show()};
g.h.unload=function(){this.player.showControls();this.T.hide()};g.qA("miniplayer",ssF);})(_yt_player);
